### ISSUE TITLE
How stable is this project?

### ISSUE THREAD

**Issue by pnegahdar** [peterbourgon/raft#6]
Hi! Thanks for the work on this. I wanted to use it because it seems like a cleaner raft implementation than the ones I've seen. Can you comment on how stable/complete it is to use on a production software?  Want to port https://github.com/pnegahdar/sporedock over to this.

**Comment by peterbourgon** [comment]
This was basically a research project, and it's not feature-complete. I don't recommend you use it :)

I can recommend [the more recent CoreOS Raft](https://github.com/coreos/etcd/tree/master/raft), used in etcd; and/or [HashiCorp's Raft](https://github.com/hashicorp/raft), used in Consul.

**Comment by pnegahdar** [comment]
Thanks.
