### ISSUE TITLE
Joint consensus Issue

### ISSUE THREAD

**Issue by txm119161336** [peterbourgon/raft#9]
if originally , we have
{s1,s2,s3}
then the joining server config like {s1,s2,s3,s4,s5} , this config will send to leader , leader will have two collections,one of which keeps the old config ,and one of which keeps  the new config , the new config will be  {s1,s2,s3,s4,s5} ,then it mark the local state  as Cold_new. after that leader sent appendrequest(including the union collect of old and new ) to followers , follower will append entry ,take effect the new config immediately without confirming  the comittment of the entry. leader received the response ,then  commit entry ,change the status to new , reset old peers to new peers ,empty the new peers collection , But i dont know why you do it like this ,could you tell me why ? For vote part ,keeping old peers can handle votes from old peers ,if it is new peers ,use new rule (new quorum size ) ,why? let'say s1 is the leader ,and 2 new servers s4,s5 join the cluster ,then s1 partition for a while, so that s1 ,s4,s5 is still a cluster ,becuase use the new rule ,its quorum is 3, For s2,s3, they restart the election ,to have a new leader(s2 or s3 eventually) ,because they dont know s4,s5 . it seems this way can not prevent issue happening .

**Comment by peterbourgon** [comment]
This repo is unmaintained.
